2024-05-15 19:53:55,155 INFO    MainThread:70217 [wandb_setup.py:_flush():76] Configure stats pid to 70217
2024-05-15 19:53:55,155 INFO    MainThread:70217 [wandb_setup.py:_flush():76] Loading settings from /Users/lisa/.config/wandb/settings
2024-05-15 19:53:55,155 INFO    MainThread:70217 [wandb_setup.py:_flush():76] Loading settings from /Users/lisa/Documents/atari/wandb/settings
2024-05-15 19:53:55,155 INFO    MainThread:70217 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-15 19:53:55,155 INFO    MainThread:70217 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-15 19:53:55,155 INFO    MainThread:70217 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'models_compare.py', 'program': '/Users/lisa/Documents/atari/models_compare.py'}
2024-05-15 19:53:55,155 INFO    MainThread:70217 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-05-15 19:53:55,155 INFO    MainThread:70217 [wandb_init.py:_log_setup():506] Logging user logs to /Users/lisa/Documents/atari/wandb/run-20240515_195355-heg6b7e1/logs/debug.log
2024-05-15 19:53:55,155 INFO    MainThread:70217 [wandb_init.py:_log_setup():507] Logging internal logs to /Users/lisa/Documents/atari/wandb/run-20240515_195355-heg6b7e1/logs/debug-internal.log
2024-05-15 19:53:55,155 INFO    MainThread:70217 [wandb_init.py:init():546] calling init triggers
2024-05-15 19:53:55,156 INFO    MainThread:70217 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {'random_seed': 4157, 'learning_rate': 0.0001, 'gamma': 0.999, 'num_parallel_envs': 1, 'total_timesteps': 10000, 'eval_episodes': 10}
2024-05-15 19:53:55,156 INFO    MainThread:70217 [wandb_init.py:init():602] starting backend
2024-05-15 19:53:55,156 INFO    MainThread:70217 [wandb_init.py:init():606] setting up manager
2024-05-15 19:53:55,159 INFO    MainThread:70217 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-15 19:53:55,163 INFO    MainThread:70217 [wandb_init.py:init():613] backend started and connected
2024-05-15 19:53:55,166 INFO    MainThread:70217 [wandb_init.py:init():701] updated telemetry
2024-05-15 19:53:55,167 INFO    MainThread:70217 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2024-05-15 19:53:55,806 ERROR   MainThread:70217 [wandb_init.py:init():764] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-05-15 19:53:56,816 WARNING MsgRouterThr:70217 [router.py:message_loop():77] message_loop has been closed
